server:
  port: 8081
spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            clientId: oauth2-client-app                                        #서비스 공급자에 등록된 클라이언트 아이디
            clientSecret: qQ7cYPYopQBhaP7eTPbZzKnBVBcYkkNj                     #서비스 공급자에 등록된 클라이언트 비빌번호
            clientName: oauth2-client-app                                      #클라이언트 이름
            authorizationGrantType: authorization_code                         #OAuth 2.0 권한 부여 타입
            scope: openid,profile                                              #리소스에 접근 제한 범위
            clientAuthenticationMethod: client_secret_basic                    #클라이언트 자격증명 전송방식
            redirectUri: http://localhost:8081/login/oauth2/code/keycloak   #인가서버에서 권한 코드 부여 후 클라이언트로 리다이렉트 하는 위치
#            redirectUri: http://localhost:8081/login/v1/oauth2/code/keycloak   #인가서버에서 권한 코드 부여 후 클라이언트로 리다이렉트 하는 위치, 리다이렉트 커스텀
#            redirectUri: http://localhost:8081/client
            provider: keycloak

          google:
            client-id: 823010453529-vtpf78akl4dc0rn8s9uq649v1crtpn0t.apps.googleusercontent.com
            client-secret: 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
            scope: openid,profile,email

          naver:
            client-id: hnkdGg2kEGXFxOTI1wXY
            client-secret: 3ENfuQH8KQ
            authorization-grant-type: authorization_code
            client-name: naver-client-app
            redirect-uri: http://localhost:8081/login/oauth2/code/naver
            scope: profile,email
            #scope: openid,profile,email

        provider:   ## 공급자 설정
          keycloak:
            issuerUri: http://localhost:8080/realms/oauth2                                        #서비스 공급자 위치
            authorizationUri: http://localhost:8080/realms/oauth2/protocol/openid-connect/auth    #OAuth 2.0 권한 코드 부여 엔드 포인트
            jwkSetUri: http://localhost:8080/realms/oauth2/protocol/openid-connect/certs          #OAuth 2.0 JwkSetUri 엔드 포인트
            tokenUri: http://localhost:8080/realms/oauth2/protocol/openid-connect/token           #OAuth 2.0 토큰 엔드 포인트
            userInfoUri: http://localhost:8080/realms/oauth2/protocol/openid-connect/userinfo     #OAuth 2.0 UserInfo 엔드 포인트
            userNameAttribute: preferred_username                                                 #OAuth 2.0 사용자명을 추출하는 클레임명
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  mvc:
    static-path-pattern: /static/**